lot:
    size: <int | tamaño de cada lote>
    wait_time_seconds: <float | tiempo de espera en segundos entre lotes>
clusters:
    name: <str | nombre del cluster>
    namespaces: <List[str] | lista de namespaces>
jaime: 
    url: <str | url del backend de jaime>